pizzaria-api:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    hikari:
      maximum-pool-size: 10
  h2:
    console:
      enabled: false
      path: /h2-console
      settings:
        web-allow-others: false
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
  springdoc:
    swagger-ui:
      enabled: true
  openapi-servers-urls: ${SERVERS_URLS}